### ISSUE TITLE
Unable to install project

### ISSUE THREAD

**Issue by Exagram** [soffes/bully#2]
Can you please elaborate on "Add Vendor/Bully/Bully.xcodeproj to your Xcode project."? Are we supposed to manually create the groups Vendor/Bully, then do the drag and drop. Or are we supposed to with Finder create the folders Vendor/Bully?

Thanks.

**Comment by soffes** [comment]
Just add the Bully.xcodeproj to your Xcode project. If you keep the structure in Finder (`Vendor/Bully/`) the rest of the instructions will work. If not, you'll need adjust the header search path.
